"""
GLE BigTime Profitability Dashboard.

Run:
    streamlit run dashboard.py

Reads cached data from gle_data.json (generated by data_pull.py).
"""

import json
import os
import subprocess
import sys
from datetime import datetime

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

DATA_FILE = "gle_data.json"

# ── page config ──────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="GLE Profitability Dashboard",
    page_icon=":bar_chart:",
    layout="wide",
)

# ── load data ────────────────────────────────────────────────────────────────


@st.cache_data
def load_data(path):
    with open(path) as f:
        return json.load(f)


def refresh_data():
    """Re-run data_pull.py and reload."""
    with st.spinner("Pulling fresh data from BigTime API (may take a few minutes)..."):
        subprocess.run([sys.executable, "data_pull.py"], check=True)
    st.cache_data.clear()


# Sidebar controls
with st.sidebar:
    st.title("GLE Dashboard")

    if not os.path.exists(DATA_FILE):
        st.warning("No cached data found. Pull data first.")
        if st.button("Pull Data Now"):
            refresh_data()
            st.rerun()
        st.stop()

    if st.button("Refresh Data"):
        refresh_data()
        st.rerun()

    data = load_data(DATA_FILE)
    generated = data.get("generated", "unknown")
    try:
        gen_dt = datetime.fromisoformat(generated)
        st.caption(f"Data as of {gen_dt:%Y-%m-%d %H:%M}")
    except (ValueError, TypeError):
        st.caption(f"Data as of {generated}")

data = load_data(DATA_FILE)
summary = data["summary"]
projects_raw = data["projects"]
clients_raw = data["clients"]
staff_raw = data["staff"]
expenses_raw = data.get("expenses", [])

df_projects = pd.DataFrame(projects_raw)
df_clients = pd.DataFrame(clients_raw)
df_staff = pd.DataFrame(staff_raw)
df_expenses = pd.DataFrame(expenses_raw) if expenses_raw else pd.DataFrame()

# ── sidebar filters ──────────────────────────────────────────────────────────

with st.sidebar:
    st.subheader("Filters")

    # Client filter
    all_clients = sorted(df_projects["ClientNm"].unique())
    selected_clients = st.multiselect("Clients", all_clients, default=[])

    # Margin filter
    margin_range = st.slider(
        "Margin % range",
        min_value=-100, max_value=100, value=(-100, 100),
    )

    # Minimum revenue filter
    min_revenue = st.number_input("Min revenue ($)", value=0, step=1000)

# Apply filters
mask = pd.Series(True, index=df_projects.index)
if selected_clients:
    mask &= df_projects["ClientNm"].isin(selected_clients)
mask &= df_projects["MarginPct"].between(margin_range[0], margin_range[1])
mask &= df_projects["Revenue"] >= min_revenue

df_filtered = df_projects[mask].copy()

# ── navigation ───────────────────────────────────────────────────────────────

with st.sidebar:
    st.subheader("Views")
    view = st.radio(
        "Select view",
        [
            "Portfolio Overview",
            "Project Table",
            "Client Rollup",
            "At-Risk Projects",
            "Staff Utilization",
        ],
        label_visibility="collapsed",
    )


# ═════════════════════════════════════════════════════════════════════════════
# VIEW 1: Portfolio Overview
# ═════════════════════════════════════════════════════════════════════════════

if view == "Portfolio Overview":
    st.header("Portfolio Overview")

    # KPI row
    c1, c2, c3, c4, c5 = st.columns(5)
    filt_revenue = df_filtered["Revenue"].sum()
    filt_cost = df_filtered["TotalCost"].sum()
    filt_margin = filt_revenue - filt_cost
    filt_margin_pct = round(filt_margin / filt_revenue * 100, 1) if filt_revenue > 0 else 0
    filt_wip = df_filtered["WIP"].sum()

    c1.metric("Revenue", f"${filt_revenue:,.0f}")
    c2.metric("Total Cost", f"${filt_cost:,.0f}")
    c3.metric("Margin", f"${filt_margin:,.0f}")
    c4.metric("Margin %", f"{filt_margin_pct}%")
    c5.metric("WIP", f"${filt_wip:,.0f}")

    st.divider()

    # Charts row
    col_left, col_right = st.columns(2)

    with col_left:
        st.subheader("Revenue vs Cost by Client (Top 15)")
        top = (
            df_filtered.groupby("ClientNm")[["Revenue", "TotalCost"]]
            .sum()
            .sort_values("Revenue", ascending=False)
            .head(15)
            .reset_index()
        )
        fig = go.Figure()
        fig.add_trace(go.Bar(name="Revenue", x=top["ClientNm"], y=top["Revenue"]))
        fig.add_trace(go.Bar(name="Cost", x=top["ClientNm"], y=top["TotalCost"]))
        fig.update_layout(barmode="group", height=420, margin=dict(t=10))
        st.plotly_chart(fig, use_container_width=True)

    with col_right:
        st.subheader("Margin % Distribution")
        has_activity = df_filtered[df_filtered["Revenue"] > 0]
        if not has_activity.empty:
            fig2 = px.histogram(
                has_activity, x="MarginPct", nbins=30,
                labels={"MarginPct": "Margin %"},
            )
            fig2.add_vline(x=0, line_dash="dash", line_color="red")
            fig2.update_layout(height=420, margin=dict(t=10))
            st.plotly_chart(fig2, use_container_width=True)
        else:
            st.info("No projects with revenue in current filter.")

    # Revenue/margin scatter
    st.subheader("Revenue vs Margin by Project")
    scatter_df = df_filtered[df_filtered["Revenue"] > 0].copy()
    if not scatter_df.empty:
        fig3 = px.scatter(
            scatter_df, x="Revenue", y="Margin",
            size="HrsIn", color="MarginPct",
            hover_name="DisplayName",
            color_continuous_scale="RdYlGn",
            range_color=[-50, 50],
            labels={"Revenue": "Revenue ($)", "Margin": "Margin ($)", "MarginPct": "Margin %"},
        )
        fig3.add_hline(y=0, line_dash="dash", line_color="red")
        fig3.update_layout(height=500, margin=dict(t=10))
        st.plotly_chart(fig3, use_container_width=True)


# ═════════════════════════════════════════════════════════════════════════════
# VIEW 2: Project Table
# ═════════════════════════════════════════════════════════════════════════════

elif view == "Project Table":
    st.header("Project Detail Table")

    display_cols = [
        "DisplayName", "ClientNm", "Revenue", "LaborCost", "ExpCost",
        "TotalCost", "Margin", "MarginPct", "WIP", "HrsIn",
        "BudgetHours", "BudgetFees", "TaskCount",
    ]
    table_df = df_filtered[display_cols].copy()
    table_df = table_df.sort_values("Revenue", ascending=False)

    # Summary row
    st.caption(f"{len(table_df)} projects  |  Total Revenue: ${table_df['Revenue'].sum():,.0f}  |  Avg Margin: {table_df['MarginPct'].mean():.1f}%")

    st.dataframe(
        table_df.style.format({
            "Revenue":     "${:,.0f}",
            "LaborCost":   "${:,.0f}",
            "ExpCost":     "${:,.0f}",
            "TotalCost":   "${:,.0f}",
            "Margin":      "${:,.0f}",
            "MarginPct":   "{:.1f}%",
            "WIP":         "${:,.0f}",
            "HrsIn":       "{:,.1f}",
            "BudgetHours": "{:,.0f}",
            "BudgetFees":  "${:,.0f}",
        }).background_gradient(
            subset=["MarginPct"], cmap="RdYlGn", vmin=-50, vmax=50,
        ),
        use_container_width=True,
        height=600,
    )


# ═════════════════════════════════════════════════════════════════════════════
# VIEW 3: Client Rollup
# ═════════════════════════════════════════════════════════════════════════════

elif view == "Client Rollup":
    st.header("Client Rollup")

    client_agg = (
        df_filtered.groupby("ClientNm")
        .agg(
            Revenue=("Revenue", "sum"),
            LaborCost=("LaborCost", "sum"),
            ExpCost=("ExpCost", "sum"),
            TotalCost=("TotalCost", "sum"),
            WIP=("WIP", "sum"),
            HrsIn=("HrsIn", "sum"),
            Projects=("ProjectId", "count"),
        )
        .reset_index()
    )
    client_agg["Margin"] = client_agg["Revenue"] - client_agg["TotalCost"]
    client_agg["MarginPct"] = (
        (client_agg["Margin"] / client_agg["Revenue"] * 100)
        .fillna(0)
        .round(1)
    )
    client_agg = client_agg.sort_values("Revenue", ascending=False)

    c1, c2 = st.columns(2)
    c1.metric("Clients", len(client_agg))
    c2.metric("Total Revenue", f"${client_agg['Revenue'].sum():,.0f}")

    st.dataframe(
        client_agg.style.format({
            "Revenue":   "${:,.0f}",
            "LaborCost": "${:,.0f}",
            "ExpCost":   "${:,.0f}",
            "TotalCost": "${:,.0f}",
            "Margin":    "${:,.0f}",
            "MarginPct": "{:.1f}%",
            "WIP":       "${:,.0f}",
            "HrsIn":     "{:,.1f}",
        }).background_gradient(
            subset=["MarginPct"], cmap="RdYlGn", vmin=-50, vmax=50,
        ),
        use_container_width=True,
        height=500,
    )

    # Top/bottom clients chart
    st.subheader("Top 10 Clients by Margin %")
    with_rev = client_agg[client_agg["Revenue"] > 1000].copy()
    if not with_rev.empty:
        top10 = with_rev.nlargest(10, "MarginPct")
        bot10 = with_rev.nsmallest(10, "MarginPct")
        combined = pd.concat([top10, bot10]).drop_duplicates()
        combined = combined.sort_values("MarginPct")
        colors = ["#d62728" if v < 0 else "#2ca02c" for v in combined["MarginPct"]]
        fig = go.Figure(go.Bar(
            x=combined["MarginPct"],
            y=combined["ClientNm"],
            orientation="h",
            marker_color=colors,
            text=[f"{v:.1f}%" for v in combined["MarginPct"]],
            textposition="outside",
        ))
        fig.add_vline(x=0, line_dash="dash", line_color="gray")
        fig.update_layout(height=max(400, len(combined) * 30), margin=dict(t=10, l=200))
        st.plotly_chart(fig, use_container_width=True)


# ═════════════════════════════════════════════════════════════════════════════
# VIEW 4: At-Risk Projects
# ═════════════════════════════════════════════════════════════════════════════

elif view == "At-Risk Projects":
    st.header("At-Risk Projects")

    with st.sidebar:
        st.subheader("Risk Thresholds")
        margin_threshold = st.number_input("Margin % below", value=10)
        wip_ratio_threshold = st.number_input("WIP / Revenue above", value=0.5, step=0.1)

    # Negative or low margin
    low_margin = df_filtered[
        (df_filtered["Revenue"] > 0) & (df_filtered["MarginPct"] < margin_threshold)
    ].sort_values("MarginPct")

    # High WIP relative to invoiced
    df_wip = df_filtered[(df_filtered["Revenue"] > 0) & (df_filtered["WIP"] > 0)].copy()
    df_wip["WIPRatio"] = df_wip["WIP"] / df_wip["Revenue"]
    high_wip = df_wip[df_wip["WIPRatio"] > wip_ratio_threshold].sort_values("WIPRatio", ascending=False)

    # Budget overruns
    df_budget = df_filtered[df_filtered["BudgetHours"] > 0].copy()
    df_budget["HrsPctUsed"] = (df_budget["HrsIn"] / df_budget["BudgetHours"] * 100).round(1)
    over_budget = df_budget[df_budget["HrsPctUsed"] > 90].sort_values("HrsPctUsed", ascending=False)

    tab1, tab2, tab3 = st.tabs([
        f"Low Margin ({len(low_margin)})",
        f"High WIP ({len(high_wip)})",
        f"Over Budget ({len(over_budget)})",
    ])

    with tab1:
        if low_margin.empty:
            st.success("No low-margin projects found.")
        else:
            st.dataframe(
                low_margin[["DisplayName", "ClientNm", "Revenue", "TotalCost", "Margin", "MarginPct", "WIP"]]
                .style.format({
                    "Revenue": "${:,.0f}", "TotalCost": "${:,.0f}",
                    "Margin": "${:,.0f}", "MarginPct": "{:.1f}%", "WIP": "${:,.0f}",
                }).background_gradient(subset=["MarginPct"], cmap="RdYlGn", vmin=-50, vmax=50),
                use_container_width=True,
            )

    with tab2:
        if high_wip.empty:
            st.success("No high-WIP projects found.")
        else:
            st.dataframe(
                high_wip[["DisplayName", "ClientNm", "Revenue", "WIP", "WIPRatio"]]
                .style.format({
                    "Revenue": "${:,.0f}", "WIP": "${:,.0f}", "WIPRatio": "{:.2f}",
                }),
                use_container_width=True,
            )

    with tab3:
        if over_budget.empty:
            st.success("No over-budget projects found.")
        else:
            st.dataframe(
                over_budget[["DisplayName", "ClientNm", "HrsIn", "BudgetHours", "HrsPctUsed"]]
                .style.format({
                    "HrsIn": "{:,.1f}", "BudgetHours": "{:,.0f}", "HrsPctUsed": "{:.1f}%",
                }).background_gradient(subset=["HrsPctUsed"], cmap="OrRd", vmin=90, vmax=150),
                use_container_width=True,
            )


# ═════════════════════════════════════════════════════════════════════════════
# VIEW 5: Staff Utilization
# ═════════════════════════════════════════════════════════════════════════════

elif view == "Staff Utilization":
    st.header("Staff Utilization")

    if df_staff.empty:
        st.warning("No staff data available.")
    else:
        staff_display = df_staff[["FullName", "Title", "CostFactor", "Capacity"]].copy()
        staff_display.columns = ["Name", "Title", "Cost Rate ($/hr)", "Monthly Capacity (hrs)"]

        st.subheader("Staff Roster")
        st.dataframe(
            staff_display.style.format({
                "Cost Rate ($/hr)": "${:,.2f}",
                "Monthly Capacity (hrs)": "{:,.0f}",
            }),
            use_container_width=True,
        )

        # Cost rate comparison chart
        st.subheader("Cost Rates by Staff Member")
        fig = px.bar(
            staff_display.sort_values("Cost Rate ($/hr)", ascending=True),
            x="Cost Rate ($/hr)", y="Name",
            orientation="h",
            text="Cost Rate ($/hr)",
            color="Cost Rate ($/hr)",
            color_continuous_scale="Blues",
        )
        fig.update_traces(texttemplate="$%{text:,.2f}", textposition="outside")
        fig.update_layout(height=max(300, len(staff_display) * 40), margin=dict(t=10, l=150))
        st.plotly_chart(fig, use_container_width=True)

    # If we have expense data, show expense breakdown
    if not df_expenses.empty:
        st.subheader("Expense Summary (Last 365 Days)")
        exp_total = df_expenses["CostIN"].sum() if "CostIN" in df_expenses.columns else 0
        st.metric("Total Expenses", f"${exp_total:,.0f}")

        if "CatNm" in df_expenses.columns:
            cat_totals = (
                df_expenses.groupby("CatNm")["CostIN"]
                .sum()
                .sort_values(ascending=False)
                .reset_index()
            )
            fig2 = px.pie(cat_totals, values="CostIN", names="CatNm", hole=0.4)
            fig2.update_layout(height=400, margin=dict(t=10))
            st.plotly_chart(fig2, use_container_width=True)
