"""
GLE BigTime Profitability Dashboard.

Run:
    python -m streamlit run dashboard.py

Reads cached data from gle_data.json (generated by data_pull.py).
"""

import json
import os
import subprocess
import sys
from datetime import datetime

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from query_engine import query_with_llm, keyword_parse, execute_query

DATA_FILE = "gle_data.json"

# ── page config ──────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="GLE Profitability Dashboard",
    page_icon=":bar_chart:",
    layout="wide",
)

# ── load data ────────────────────────────────────────────────────────────────


@st.cache_data
def load_data(path):
    with open(path) as f:
        return json.load(f)


def refresh_data():
    """Re-run data_pull.py and reload."""
    with st.spinner("Pulling fresh data from BigTime API (may take a few minutes)..."):
        subprocess.run([sys.executable, "data_pull.py"], check=True)
    st.cache_data.clear()


# Sidebar controls
with st.sidebar:
    st.title("GLE Dashboard")

    if not os.path.exists(DATA_FILE):
        st.warning("No cached data found. Pull data first.")
        if st.button("Pull Data Now"):
            refresh_data()
            st.rerun()
        st.stop()

    if st.button("Refresh Data"):
        refresh_data()
        st.rerun()

    data = load_data(DATA_FILE)
    generated = data.get("generated", "unknown")
    try:
        gen_dt = datetime.fromisoformat(generated)
        st.caption(f"Data as of {gen_dt:%Y-%m-%d %H:%M}")
    except (ValueError, TypeError):
        st.caption(f"Data as of {generated}")

data = load_data(DATA_FILE)
summary = data["summary"]
projects_raw = data["projects"]
clients_raw = data["clients"]
staff_raw = data["staff"]
expenses_raw = data.get("expenses", [])
invoices_raw = data.get("invoices", [])
project_types = data.get("project_types", {})

df_projects = pd.DataFrame(projects_raw)
df_clients = pd.DataFrame(clients_raw)
df_staff = pd.DataFrame(staff_raw)
df_expenses = pd.DataFrame(expenses_raw) if expenses_raw else pd.DataFrame()
df_invoices = pd.DataFrame(invoices_raw) if invoices_raw else pd.DataFrame()

# Build list of project type names for filters
type_names = sorted(set(df_projects["TypeName"].unique())) if "TypeName" in df_projects.columns else []

# ── sidebar filters ──────────────────────────────────────────────────────────

with st.sidebar:
    st.subheader("Filters")

    # Project type filter
    if type_names:
        selected_types = st.multiselect("Project Type", type_names, default=[])

    # Client filter
    all_clients = sorted(df_projects["ClientNm"].unique())
    selected_clients = st.multiselect("Clients", all_clients, default=[])

    # Margin filter
    margin_range = st.slider(
        "Margin % range",
        min_value=-100, max_value=100, value=(-100, 100),
    )

    # Minimum revenue filter
    min_revenue = st.number_input("Min revenue ($)", value=0, step=1000)

# Apply filters
mask = pd.Series(True, index=df_projects.index)
if type_names and selected_types:
    mask &= df_projects["TypeName"].isin(selected_types)
if selected_clients:
    mask &= df_projects["ClientNm"].isin(selected_clients)
mask &= df_projects["MarginPct"].between(margin_range[0], margin_range[1])
mask &= df_projects["Revenue"] >= min_revenue

df_filtered = df_projects[mask].copy()

# ── navigation ───────────────────────────────────────────────────────────────

with st.sidebar:
    st.subheader("Views")
    view = st.radio(
        "Select view",
        [
            "Portfolio Overview",
            "Project Table",
            "Client Rollup",
            "Invoice Explorer",
            "At-Risk Projects",
            "Report Builder",
            "Ask a Question",
            "Staff Utilization",
        ],
        label_visibility="collapsed",
    )


# ═══════════════════════════════════════════════════════════════════════════════
# HELPER: format currency columns in a DataFrame for display
# ═══════════════════════════════════════════════════════════════════════════════

CURRENCY_COLS = {
    "Revenue", "LaborCost", "ExpCost", "TotalCost", "Margin", "WIP",
    "FeeWIP", "ExpWIP", "BudgetFees", "ChargeIn", "EstFee",
    "InvoiceAmt", "TotalAmt", "PaidAmt", "TotalAmtDue", "Subtotal",
}
PCT_COLS = {"MarginPct", "HrsPctUsed"}
HOUR_COLS = {"HrsIn", "BudgetHours", "EstHrs"}


def auto_format(df):
    """Build a style format dict based on column names."""
    fmt = {}
    for col in df.columns:
        if col in CURRENCY_COLS:
            fmt[col] = "${:,.0f}"
        elif col in PCT_COLS:
            fmt[col] = "{:.1f}%"
        elif col in HOUR_COLS:
            fmt[col] = "{:,.1f}"
    return fmt


# ═══════════════════════════════════════════════════════════════════════════════
# VIEW 1: Portfolio Overview
# ═══════════════════════════════════════════════════════════════════════════════

if view == "Portfolio Overview":
    st.header("Portfolio Overview")

    # KPI row
    c1, c2, c3, c4, c5 = st.columns(5)
    filt_revenue = df_filtered["Revenue"].sum()
    filt_cost = df_filtered["TotalCost"].sum()
    filt_margin = filt_revenue - filt_cost
    filt_margin_pct = round(filt_margin / filt_revenue * 100, 1) if filt_revenue > 0 else 0
    filt_wip = df_filtered["WIP"].sum()

    c1.metric("Revenue", f"${filt_revenue:,.0f}")
    c2.metric("Total Cost", f"${filt_cost:,.0f}")
    c3.metric("Margin", f"${filt_margin:,.0f}")
    c4.metric("Margin %", f"{filt_margin_pct}%")
    c5.metric("WIP", f"${filt_wip:,.0f}")

    st.divider()

    # Charts row
    col_left, col_right = st.columns(2)

    with col_left:
        st.subheader("Revenue vs Cost by Client (Top 15)")
        top = (
            df_filtered.groupby("ClientNm")[["Revenue", "TotalCost"]]
            .sum()
            .sort_values("Revenue", ascending=False)
            .head(15)
            .reset_index()
        )
        fig = go.Figure()
        fig.add_trace(go.Bar(name="Revenue", x=top["ClientNm"], y=top["Revenue"]))
        fig.add_trace(go.Bar(name="Cost", x=top["ClientNm"], y=top["TotalCost"]))
        fig.update_layout(barmode="group", height=420, margin=dict(t=10))
        st.plotly_chart(fig, use_container_width=True)

    with col_right:
        st.subheader("Margin % Distribution")
        has_activity = df_filtered[df_filtered["Revenue"] > 0]
        if not has_activity.empty:
            fig2 = px.histogram(
                has_activity, x="MarginPct", nbins=30,
                labels={"MarginPct": "Margin %"},
            )
            fig2.add_vline(x=0, line_dash="dash", line_color="red")
            fig2.update_layout(height=420, margin=dict(t=10))
            st.plotly_chart(fig2, use_container_width=True)
        else:
            st.info("No projects with revenue in current filter.")

    # Revenue/margin scatter
    st.subheader("Revenue vs Margin by Project")
    scatter_df = df_filtered[df_filtered["Revenue"] > 0].copy()
    if not scatter_df.empty:
        fig3 = px.scatter(
            scatter_df, x="Revenue", y="Margin",
            size="HrsIn", color="MarginPct",
            hover_name="DisplayName",
            color_continuous_scale="RdYlGn",
            range_color=[-50, 50],
            labels={"Revenue": "Revenue ($)", "Margin": "Margin ($)", "MarginPct": "Margin %"},
        )
        fig3.add_hline(y=0, line_dash="dash", line_color="red")
        fig3.update_layout(height=500, margin=dict(t=10))
        st.plotly_chart(fig3, use_container_width=True)


# ═══════════════════════════════════════════════════════════════════════════════
# VIEW 2: Project Table
# ═══════════════════════════════════════════════════════════════════════════════

elif view == "Project Table":
    st.header("Project Detail Table")

    display_cols = [
        "DisplayName", "ClientNm", "TypeName", "Revenue", "LaborCost", "ExpCost",
        "TotalCost", "Margin", "MarginPct", "WIP", "HrsIn",
        "BudgetHours", "BudgetFees", "TaskCount",
    ]
    available_cols = [c for c in display_cols if c in df_filtered.columns]
    table_df = df_filtered[available_cols].copy()
    table_df = table_df.sort_values("Revenue", ascending=False)

    # Summary row
    st.caption(f"{len(table_df)} projects  |  Total Revenue: ${table_df['Revenue'].sum():,.0f}  |  Avg Margin: {table_df['MarginPct'].mean():.1f}%")

    st.dataframe(
        table_df.style.format(auto_format(table_df)).background_gradient(
            subset=["MarginPct"], cmap="RdYlGn", vmin=-50, vmax=50,
        ),
        use_container_width=True,
        height=600,
    )


# ═══════════════════════════════════════════════════════════════════════════════
# VIEW 3: Client Rollup
# ═══════════════════════════════════════════════════════════════════════════════

elif view == "Client Rollup":
    st.header("Client Rollup")

    client_agg = (
        df_filtered.groupby("ClientNm")
        .agg(
            Revenue=("Revenue", "sum"),
            LaborCost=("LaborCost", "sum"),
            ExpCost=("ExpCost", "sum"),
            TotalCost=("TotalCost", "sum"),
            WIP=("WIP", "sum"),
            HrsIn=("HrsIn", "sum"),
            Projects=("ProjectId", "count"),
        )
        .reset_index()
    )
    client_agg["Margin"] = client_agg["Revenue"] - client_agg["TotalCost"]
    client_agg["MarginPct"] = (
        (client_agg["Margin"] / client_agg["Revenue"] * 100)
        .fillna(0)
        .round(1)
    )
    client_agg = client_agg.sort_values("Revenue", ascending=False)

    c1, c2 = st.columns(2)
    c1.metric("Clients", len(client_agg))
    c2.metric("Total Revenue", f"${client_agg['Revenue'].sum():,.0f}")

    st.dataframe(
        client_agg.style.format(auto_format(client_agg)).background_gradient(
            subset=["MarginPct"], cmap="RdYlGn", vmin=-50, vmax=50,
        ),
        use_container_width=True,
        height=500,
    )

    # Top/bottom clients chart
    st.subheader("Top 10 Clients by Margin %")
    with_rev = client_agg[client_agg["Revenue"] > 1000].copy()
    if not with_rev.empty:
        top10 = with_rev.nlargest(10, "MarginPct")
        bot10 = with_rev.nsmallest(10, "MarginPct")
        combined = pd.concat([top10, bot10]).drop_duplicates()
        combined = combined.sort_values("MarginPct")
        colors = ["#d62728" if v < 0 else "#2ca02c" for v in combined["MarginPct"]]
        fig = go.Figure(go.Bar(
            x=combined["MarginPct"],
            y=combined["ClientNm"],
            orientation="h",
            marker_color=colors,
            text=[f"{v:.1f}%" for v in combined["MarginPct"]],
            textposition="outside",
        ))
        fig.add_vline(x=0, line_dash="dash", line_color="gray")
        fig.update_layout(height=max(400, len(combined) * 30), margin=dict(t=10, l=200))
        st.plotly_chart(fig, use_container_width=True)


# ═══════════════════════════════════════════════════════════════════════════════
# VIEW 4: Invoice Explorer
# ═══════════════════════════════════════════════════════════════════════════════

elif view == "Invoice Explorer":
    st.header("Invoice Explorer")

    if df_invoices.empty:
        st.warning("No invoice data available. Refresh data to pull invoices from BigTime.")
    else:
        # Invoice filters
        col1, col2, col3 = st.columns(3)

        with col1:
            inv_years = sorted(pd.to_datetime(df_invoices["InvoiceDt"], errors="coerce").dt.year.dropna().unique().astype(int), reverse=True)
            selected_year = st.selectbox("Invoice Year", ["All"] + [str(y) for y in inv_years])

        with col2:
            inv_statuses = sorted(df_invoices["StatusTxt"].unique())
            selected_status = st.selectbox("Status", ["All"] + list(inv_statuses))

        with col3:
            inv_clients = sorted(df_invoices["ClientNm"].unique())
            selected_inv_client = st.selectbox("Client", ["All"] + list(inv_clients))

        # Apply invoice filters
        df_inv = df_invoices.copy()
        df_inv["_InvDate"] = pd.to_datetime(df_inv["InvoiceDt"], errors="coerce")

        if selected_year != "All":
            df_inv = df_inv[df_inv["_InvDate"].dt.year == int(selected_year)]
        if selected_status != "All":
            df_inv = df_inv[df_inv["StatusTxt"] == selected_status]
        if selected_inv_client != "All":
            df_inv = df_inv[df_inv["ClientNm"] == selected_inv_client]

        # KPIs
        k1, k2, k3, k4 = st.columns(4)
        k1.metric("Invoices", f"{len(df_inv):,}")
        k2.metric("Total Invoiced", f"${df_inv['InvoiceAmt'].sum():,.0f}")
        k3.metric("Total Paid", f"${df_inv['PaidAmt'].sum():,.0f}")
        k4.metric("Outstanding", f"${df_inv['TotalAmtDue'].sum():,.0f}")

        st.divider()

        # Invoice table
        inv_display = [
            "InvoiceNbr", "InvoiceDt", "ClientNm", "DName",
            "InvoiceAmt", "PaidAmt", "TotalAmtDue", "StatusTxt",
            "TermsNm", "DaysOutstanding", "ARPeriodNm",
        ]
        available = [c for c in inv_display if c in df_inv.columns]
        show_df = df_inv[available].sort_values("InvoiceDt", ascending=False).drop(columns=["_InvDate"], errors="ignore") if "_InvDate" in df_inv.columns else df_inv[available].sort_values("InvoiceDt", ascending=False)

        st.dataframe(
            show_df.style.format(auto_format(show_df)),
            use_container_width=True,
            height=500,
        )

        # Monthly trend chart
        if not df_inv.empty and "_InvDate" in df_inv.columns:
            st.subheader("Monthly Invoice Trend")
            monthly = df_inv.copy()
            monthly["Month"] = monthly["_InvDate"].dt.to_period("M").astype(str)
            monthly_agg = monthly.groupby("Month")["InvoiceAmt"].sum().reset_index()
            fig = px.bar(monthly_agg, x="Month", y="InvoiceAmt",
                         labels={"InvoiceAmt": "Amount ($)", "Month": "Month"})
            fig.update_layout(height=350, margin=dict(t=10))
            st.plotly_chart(fig, use_container_width=True)


# ═══════════════════════════════════════════════════════════════════════════════
# VIEW 5: At-Risk Projects
# ═══════════════════════════════════════════════════════════════════════════════

elif view == "At-Risk Projects":
    st.header("At-Risk Projects")

    with st.sidebar:
        st.subheader("Risk Thresholds")
        margin_threshold = st.number_input("Margin % below", value=10)
        wip_ratio_threshold = st.number_input("WIP / Revenue above", value=0.5, step=0.1)

    # Negative or low margin
    low_margin = df_filtered[
        (df_filtered["Revenue"] > 0) & (df_filtered["MarginPct"] < margin_threshold)
    ].sort_values("MarginPct")

    # High WIP relative to invoiced
    df_wip = df_filtered[(df_filtered["Revenue"] > 0) & (df_filtered["WIP"] > 0)].copy()
    df_wip["WIPRatio"] = df_wip["WIP"] / df_wip["Revenue"]
    high_wip = df_wip[df_wip["WIPRatio"] > wip_ratio_threshold].sort_values("WIPRatio", ascending=False)

    # Budget overruns
    df_budget = df_filtered[df_filtered["BudgetHours"] > 0].copy()
    df_budget["HrsPctUsed"] = (df_budget["HrsIn"] / df_budget["BudgetHours"] * 100).round(1)
    over_budget = df_budget[df_budget["HrsPctUsed"] > 90].sort_values("HrsPctUsed", ascending=False)

    tab1, tab2, tab3 = st.tabs([
        f"Low Margin ({len(low_margin)})",
        f"High WIP ({len(high_wip)})",
        f"Over Budget ({len(over_budget)})",
    ])

    with tab1:
        if low_margin.empty:
            st.success("No low-margin projects found.")
        else:
            cols = ["DisplayName", "ClientNm", "TypeName", "Revenue", "TotalCost", "Margin", "MarginPct", "WIP"]
            available = [c for c in cols if c in low_margin.columns]
            st.dataframe(
                low_margin[available]
                .style.format(auto_format(low_margin[available]))
                .background_gradient(subset=["MarginPct"], cmap="RdYlGn", vmin=-50, vmax=50),
                use_container_width=True,
            )

    with tab2:
        if high_wip.empty:
            st.success("No high-WIP projects found.")
        else:
            st.dataframe(
                high_wip[["DisplayName", "ClientNm", "Revenue", "WIP", "WIPRatio"]]
                .style.format({
                    "Revenue": "${:,.0f}", "WIP": "${:,.0f}", "WIPRatio": "{:.2f}",
                }),
                use_container_width=True,
            )

    with tab3:
        if over_budget.empty:
            st.success("No over-budget projects found.")
        else:
            st.dataframe(
                over_budget[["DisplayName", "ClientNm", "HrsIn", "BudgetHours", "HrsPctUsed"]]
                .style.format({
                    "HrsIn": "{:,.1f}", "BudgetHours": "{:,.0f}", "HrsPctUsed": "{:.1f}%",
                }).background_gradient(subset=["HrsPctUsed"], cmap="OrRd", vmin=90, vmax=150),
                use_container_width=True,
            )


# ═══════════════════════════════════════════════════════════════════════════════
# VIEW 6: Report Builder
# ═══════════════════════════════════════════════════════════════════════════════

elif view == "Report Builder":
    st.header("Report Builder")
    st.caption("Build custom reports by selecting a data source, filters, and columns.")

    # Data source
    data_source = st.radio("Data source", ["Projects", "Invoices", "Projects + Invoices (combined)"], horizontal=True)

    if data_source == "Projects":
        base_df = df_filtered.copy()
        all_columns = list(df_filtered.columns)
    elif data_source == "Invoices":
        base_df = df_invoices.copy()
        all_columns = list(df_invoices.columns)
    else:
        # Combined: join invoices with project data (exclude overlapping columns)
        proj_extra = [c for c in df_projects.columns if c not in df_invoices.columns]
        if "ProjectId" not in proj_extra:
            proj_extra.append("ProjectId")
        base_df = df_invoices.merge(
            df_projects[proj_extra].drop_duplicates(subset=["ProjectId"]),
            left_on="ProjectSid",
            right_on="ProjectId",
            how="left",
        )
        all_columns = list(base_df.columns)

    col_left, col_right = st.columns([1, 2])

    with col_left:
        st.subheader("Filters")

        # Project type filter (for projects and combined)
        if "TypeName" in base_df.columns and type_names:
            rb_types = st.multiselect("Project Type", type_names, default=[], key="rb_types")
            if rb_types:
                base_df = base_df[base_df["TypeName"].isin(rb_types)]

        # Client filter
        if "ClientNm" in base_df.columns:
            rb_clients = st.multiselect("Client", sorted(base_df["ClientNm"].unique()), default=[], key="rb_clients")
            if rb_clients:
                base_df = base_df[base_df["ClientNm"].isin(rb_clients)]

        # Date filter (for invoices)
        if "InvoiceDt" in base_df.columns:
            base_df["_dt"] = pd.to_datetime(base_df["InvoiceDt"], errors="coerce")
            years = sorted(base_df["_dt"].dt.year.dropna().unique().astype(int), reverse=True)
            rb_year = st.selectbox("Invoice Year", ["All"] + [str(y) for y in years], key="rb_year")
            if rb_year != "All":
                base_df = base_df[base_df["_dt"].dt.year == int(rb_year)]
            base_df = base_df.drop(columns=["_dt"])

        # Revenue threshold
        if "Revenue" in base_df.columns:
            rb_min_rev = st.number_input("Min Revenue ($)", value=0, step=1000, key="rb_min_rev")
            if rb_min_rev > 0:
                base_df = base_df[base_df["Revenue"] >= rb_min_rev]

        # Margin threshold
        if "MarginPct" in base_df.columns:
            rb_margin = st.slider("Margin % range", -100, 100, (-100, 100), key="rb_margin")
            if rb_margin != (-100, 100):
                base_df = base_df[base_df["MarginPct"].between(rb_margin[0], rb_margin[1])]

        # Status filter (invoices)
        if "StatusTxt" in base_df.columns:
            statuses = sorted(base_df["StatusTxt"].unique())
            rb_status = st.multiselect("Invoice Status", statuses, default=[], key="rb_status")
            if rb_status:
                base_df = base_df[base_df["StatusTxt"].isin(rb_status)]

    with col_right:
        st.subheader("Columns & Display")

        # Sensible defaults based on data source
        if data_source == "Projects":
            default_cols = ["ClientNm", "ProjectNm", "TypeName", "HrsIn", "Revenue", "LaborCost", "ExpCost", "Margin", "MarginPct"]
        elif data_source == "Invoices":
            default_cols = ["InvoiceNbr", "InvoiceDt", "ClientNm", "DName", "InvoiceAmt", "PaidAmt", "TotalAmtDue", "StatusTxt"]
        else:
            default_cols = ["ClientNm", "ProjectNm", "TypeName", "InvoiceDt", "InvoiceAmt", "HrsIn", "Revenue", "LaborCost", "ExpCost", "Margin"]

        # Remove internal columns
        display_options = [c for c in all_columns if not c.startswith("_") and c not in ("ProjectId", "ClientId", "TypeId", "InvoiceSid", "ClientSid", "ProjectSid")]
        defaults_available = [c for c in default_cols if c in display_options]

        selected_cols = st.multiselect("Select columns", display_options, default=defaults_available, key="rb_cols")

        # Sort option
        sort_col = st.selectbox("Sort by", ["None"] + (selected_cols or []), key="rb_sort")
        sort_order = st.radio("Sort order", ["Descending", "Ascending"], horizontal=True, key="rb_order")

        # Group by
        group_options = [c for c in selected_cols if c in ("ClientNm", "TypeName", "StatusTxt", "ARPeriodNm", "TermsNm", "BillingRate")]
        group_col = st.selectbox("Group by (optional)", ["None"] + group_options, key="rb_group")

    # Build and display report
    if selected_cols:
        report_df = base_df[[c for c in selected_cols if c in base_df.columns]].copy()

        if group_col != "None" and group_col in report_df.columns:
            # Aggregate: sum numeric, count rows
            numeric_cols = report_df.select_dtypes(include="number").columns.tolist()
            agg_dict = {c: "sum" for c in numeric_cols if c != group_col}
            agg_dict["_count"] = (report_df.columns[0], "count")
            # Use groupby with named aggregation
            grouped = base_df.groupby(group_col)
            agg_result = {}
            for col in selected_cols:
                if col == group_col:
                    continue
                if col in base_df.columns and pd.api.types.is_numeric_dtype(base_df[col]):
                    agg_result[col] = (col, "sum")
            agg_result["Count"] = (selected_cols[0] if selected_cols[0] != group_col else selected_cols[-1], "count")
            report_df = grouped.agg(**agg_result).reset_index()
            # Recompute MarginPct if present
            if "MarginPct" in report_df.columns and "Revenue" in report_df.columns and "TotalCost" in report_df.columns:
                report_df["MarginPct"] = ((report_df["Revenue"] - report_df["TotalCost"]) / report_df["Revenue"] * 100).fillna(0).round(1)

        if sort_col != "None" and sort_col in report_df.columns:
            report_df = report_df.sort_values(sort_col, ascending=(sort_order == "Ascending"))

        st.divider()
        st.subheader(f"Results ({len(report_df)} rows)")
        st.dataframe(
            report_df.style.format(auto_format(report_df)),
            use_container_width=True,
            height=500,
        )

        # Download button
        csv = report_df.to_csv(index=False)
        st.download_button("Download CSV", csv, "report.csv", "text/csv")
    else:
        st.info("Select at least one column to display.")


# ═══════════════════════════════════════════════════════════════════════════════
# VIEW 7: Ask a Question (Natural Language Query)
# ═══════════════════════════════════════════════════════════════════════════════

elif view == "Ask a Question":
    st.header("Ask a Question")
    st.caption("Type a question in plain English and get a report back. Uses AI to interpret your request.")

    # Example queries
    with st.expander("Example questions you can ask"):
        st.markdown("""
- **Show me all GI CSA projects with their client name, hours, revenue, labor cost, and profit**
- **Which projects have negative margin?**
- **Show invoices sent in 2025 for Safety projects**
- **Top 10 projects by revenue**
- **Total invoiced by client in 2025**
- **Unpaid invoices over 30 days outstanding**
- **Construction Safety projects with revenue over $10,000**
""")

    question = st.text_area("Your question:", placeholder="e.g., Show me GI CSA projects with invoices sent in 2025...", height=80)

    if st.button("Run Query", type="primary") and question.strip():
        with st.spinner("Processing your question..."):
            # Try LLM first, fall back to keyword parser
            spec, error = query_with_llm(question, type_names)
            used_ai = True

            if error:
                # Fall back to keyword parser
                st.info(f"AI query unavailable ({error.split('.')[0]}). Using keyword parser instead.")
                spec = keyword_parse(question, type_names)
                used_ai = False

            if spec:
                # Show the interpreted query
                with st.expander("Query interpretation" + (" (AI)" if used_ai else " (keyword)")):
                    st.json(spec)

                result_df, title, exec_error = execute_query(spec, df_projects, df_invoices)

                if exec_error:
                    st.error(f"Query execution error: {exec_error}")
                elif result_df is not None and not result_df.empty:
                    st.subheader(title)
                    st.caption(f"{len(result_df)} rows")
                    st.dataframe(
                        result_df.style.format(auto_format(result_df)),
                        use_container_width=True,
                        height=min(600, max(200, len(result_df) * 35 + 50)),
                    )

                    # Download
                    csv = result_df.to_csv(index=False)
                    st.download_button("Download CSV", csv, "query_result.csv", "text/csv")
                else:
                    st.warning("No results found matching your query.")

    # Quick presets
    st.divider()
    st.subheader("Quick Reports")
    preset_col1, preset_col2, preset_col3 = st.columns(3)

    presets = {
        "GI CSA Profitability": {
            "table": "projects",
            "filters": [{"column": "TypeName", "op": "eq", "value": "GI CSA"}],
            "columns": ["ClientNm", "ProjectNm", "HrsIn", "Revenue", "LaborCost", "ExpCost", "Margin", "MarginPct"],
            "sort_by": "Revenue",
            "sort_asc": False,
            "title": "GI CSA Project Profitability",
        },
        "Unpaid Invoices": {
            "table": "invoices",
            "filters": [{"column": "IsPaid", "op": "eq", "value": False}, {"column": "TotalAmtDue", "op": "gt", "value": 0}],
            "columns": ["InvoiceNbr", "InvoiceDt", "ClientNm", "DName", "InvoiceAmt", "PaidAmt", "TotalAmtDue", "DaysOutstanding", "ARPeriodNm"],
            "sort_by": "TotalAmtDue",
            "sort_asc": False,
            "title": "Unpaid Invoices",
        },
        "2025 Invoices by Type": {
            "table": "combined",
            "filters": [{"column": "InvoiceDt", "op": "year", "value": 2025}],
            "columns": ["TypeName", "InvoiceAmt"],
            "group_by": "TypeName",
            "agg": {"InvoiceAmt": "sum"},
            "sort_by": "InvoiceAmt",
            "sort_asc": False,
            "title": "2025 Total Invoiced by Project Type",
        },
    }

    for i, (name, spec) in enumerate(presets.items()):
        col = [preset_col1, preset_col2, preset_col3][i % 3]
        with col:
            if st.button(name, key=f"preset_{i}"):
                result_df, title, exec_error = execute_query(spec, df_projects, df_invoices)
                if exec_error:
                    st.error(exec_error)
                elif result_df is not None and not result_df.empty:
                    st.subheader(title)
                    st.dataframe(
                        result_df.style.format(auto_format(result_df)),
                        use_container_width=True,
                    )


# ═══════════════════════════════════════════════════════════════════════════════
# VIEW 8: Staff Utilization
# ═══════════════════════════════════════════════════════════════════════════════

elif view == "Staff Utilization":
    st.header("Staff Utilization")

    if df_staff.empty:
        st.warning("No staff data available.")
    else:
        staff_display = df_staff[["FullName", "Title", "CostFactor", "Capacity"]].copy()
        staff_display.columns = ["Name", "Title", "Cost Rate ($/hr)", "Monthly Capacity (hrs)"]

        st.subheader("Staff Roster")
        st.dataframe(
            staff_display.style.format({
                "Cost Rate ($/hr)": "${:,.2f}",
                "Monthly Capacity (hrs)": "{:,.0f}",
            }),
            use_container_width=True,
        )

        # Cost rate comparison chart
        st.subheader("Cost Rates by Staff Member")
        fig = px.bar(
            staff_display.sort_values("Cost Rate ($/hr)", ascending=True),
            x="Cost Rate ($/hr)", y="Name",
            orientation="h",
            text="Cost Rate ($/hr)",
            color="Cost Rate ($/hr)",
            color_continuous_scale="Blues",
        )
        fig.update_traces(texttemplate="$%{text:,.2f}", textposition="outside")
        fig.update_layout(height=max(300, len(staff_display) * 40), margin=dict(t=10, l=150))
        st.plotly_chart(fig, use_container_width=True)

    # If we have expense data, show expense breakdown
    if not df_expenses.empty:
        st.subheader("Expense Summary (Last 365 Days)")
        exp_total = df_expenses["CostIN"].sum() if "CostIN" in df_expenses.columns else 0
        st.metric("Total Expenses", f"${exp_total:,.0f}")

        if "CatNm" in df_expenses.columns:
            cat_totals = (
                df_expenses.groupby("CatNm")["CostIN"]
                .sum()
                .sort_values(ascending=False)
                .reset_index()
            )
            fig2 = px.pie(cat_totals, values="CostIN", names="CatNm", hole=0.4)
            fig2.update_layout(height=400, margin=dict(t=10))
            st.plotly_chart(fig2, use_container_width=True)
